CREATE TABLE IF NOT EXISTS triage_data (
    anomaly_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    anomaly_date TEXT,
    anomaly_start_time TEXT,
    anomaly_end_time TEXT,
    delay_duration INTEGER,
    equipment_details TEXT,
    summary TEXT,
    cause TEXT,
    component TEXT,
    failure_mode TEXT,
    reasoning_rationale TEXT,
    recommendations TEXT,
    equip_op_status TEXT,
    user_summary_one TEXT,
    user_summary_two TEXT,
    tags_set_one TEXT[],
    tags_rationale_one TEXT,
    tags_set_two TEXT[],
    tags_rationale_two TEXT,
    tags_set_three TEXT[],
    tags_rationale_three TEXT,
    source_name TEXT,
    source_type TEXT,
    contributor_tags TEXT[], 
    search_key_words TEXT[],
    facility_zone TEXT,
    billet_size TEXT,
    proc_flag INTEGER
);

---
CREATE TABLE IF NOT EXISTS jindal_maintenance_data (
    anomaly_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    anomaly_date TEXT,
    anomaly_start_time TEXT,
    anomaly_end_time TEXT,
    delay_duration INTEGER,
    equipment_details TEXT,
    summary TEXT,
    cause TEXT,
    component TEXT,
    sub_component TEXT,
    failure_mode TEXT,
    reason TEXT,
    recommendation TEXT,
    equip_op_status TEXT,
    capa_summary TEXT,
    delay_summary TEXT,
    tags_set_one TEXT[],
    tags_rationale_one TEXT,
    tags_set_two TEXT[],
    tags_rationale_two TEXT,
    source_name TEXT,
    source_type TEXT,
    contributor_tags TEXT[], 
    search_key_words TEXT[],
    facility_zone TEXT,
    billet_size TEXT,
    proc_flag INTEGER
);
-- analysis data table
CREATE TABLE IF NOT EXISTS analysis_data (
    analysis_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iteration_num INTEGER,
    anomaly_event_id BIGINT NOT NULL, -- Foreign key
    analysis_summary TEXT,
    tags_data_summary TEXT[],
    cause TEXT,
    component TEXT,
    failure_mode TEXT,
    reasoning_rationale TEXT,
    equip_op_status_summary TEXT,
    false_positive_flag BOOLEAN,
    fp_confidence_score REAL, -- For floating point numbers like 0.0 to 1.0
    tags_trends TEXT,
    tags_set_one TEXT[],
    tags_rationale_one TEXT,
    tags_set_two TEXT[],
    tags_rationale_two TEXT,
    tags_set_three TEXT[],
    tags_rationale_three TEXT,
    images_locations TEXT, -- Could be a path, URL, or comma-separated list if multiple
    search_key_words TEXT[],

    CONSTRAINT fk_anomaly_event
        FOREIGN KEY(anomaly_event_id)
        REFERENCES triage_data(anomaly_event_id)
        ON DELETE CASCADE -- Or ON DELETE RESTRICT, ON DELETE SET NULL (if anomaly_event_id can be NULL)
        -- ON UPDATE CASCADE -- Optional: if anomaly_event_id in triage_data could change (less common for PKs)
);